---
- name: Configure dehydrated
  ansible.builtin.template:
    src: config.j2
    dest: '/etc/dehydrated/config'
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: Config domains
  ansible.builtin.template:
    src: domains.txt.j2
    dest: '/etc/dehydrated/domains.txt'
    owner: root
    group: root
    mode: '0644'
    backup: true

# we want to only create the logfile if it dont exist
- name: Get filestatus
  ansible.builtin.stat:
    path: "/var/log/dehydrated.log"
  register: p

- name: Create logfile
  ansible.builtin.file:
    state: touch
    path: "/var/log/dehydrated.log"
    owner: root
    group: syslogd
    mode: '0774'
  when: not p.stat.exists
...
