---
- name: Create dehydrated http-01 directory
  ansible.builtin.file:
    state: directory
    path: "{{ dehydrated_www_dir | default(default.dehydrated_www_dir) }}"
    owner: root
    group: root
    mode: '0755'

- name: Copy apache config
  ansible.builtin.template:
    src: dehydrated.conf.j2
    dest: '/etc/httpd/conf/vhosts.d/dehydrated.conf'
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: Remap certificate
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/vhosts.d/ipfire-interface-ssl.conf
    insertafter: '    SSLCertificateKeyFile /etc/httpd/server-ecdsa.key'
    line: "    SSLCertificateFile /etc/dehydrated/certs/{{ cloudinit_fqdn }}/cert.pem"
  notify: Restart apache

- name: Remap key
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/vhosts.d/ipfire-interface-ssl.conf
    insertafter: '    SSLCertificateFile /etc/dehydrated/certs/{{ cloudinit_fqdn }}/cert.pem'
    line: "    SSLCertificateKeyFile /etc/dehydrated/certs/{{ cloudinit_fqdn }}/privkey.pem"
  notify: Restart apache

- name: Remap ca-chains
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/vhosts.d/ipfire-interface-ssl.conf
    insertafter: '    SSLCertificateKeyFile /etc/dehydrated/certs/{{ cloudinit_fqdn }}/privkey.pem'
    line: "    SSLCertificateChainFile /etc/dehydrated/certs/{{ cloudinit_fqdn }}/fullchain.pem"
  notify: Restart apache
...
