---
# the ansible module wants the executable crontab so we have to create a symlink
- name: sysmlink fcrontab to crontab
  ansible.builtin.file:
    src: /usr/bin/fcrontab
    dest: /usr/bin/crontab
    owner: root
    group: root
    state: link

# Well, I have to use "--force" because my certs are only valid for one day and renew="0" dont work
- name: dehydrated cron
  ansible.builtin.cron:
    name: fdo - renew step ca certificate
    state: present
    weekday: "*"
    minute: "0"
    hour: "*/12"
    user: root
    job: "sudo /usr/bin/dehydrated --cleanup-delete  >> /var/log/dehydrated.log 2>&1 && sudo /usr/bin/dehydrated --force --cron >> /var/log/dehydrated.log 2>&1 && /etc/init.d/apache restart"
    backup: True

- name: register Terms
  ansible.builtin.shell:
    cmd: "sudo /usr/bin/dehydrated --register --accept-terms >> /var/log/dehydrated.log 2>&1"
    chdir: /usr/bin
    executable: /bin/bash

- name: get or renew certificate
  ansible.builtin.shell:
    cmd: "sudo /usr/bin/dehydrated --cleanup-delete  >> /var/log/dehydrated.log 2>&1 && sudo /usr/bin/dehydrated --force --cron >> /var/log/dehydrated.log 2>&1 && /etc/init.d/apache restart"
    chdir: /usr/bin
    executable: /bin/bash