---
- name: default configuration generic
  block:
  - name: add this plays
    debug:
      msg: "{{ lookup( 'fileglob', '*.yml' ).split(',') | reject('search', 'main.yml') | sort }}"

  - name: Add and run all plays
    include_tasks: "{{ element }}"
    with_items: "{{ lookup( 'fileglob', '*.yml' ).split(',') | reject('search', 'main.yml') | sort }}"
    loop_control:
      loop_var: element
...
